package com.celebihacker.ml.logreg;

import java.io.IOException;

import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.Reducer;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.util.Tool;
import org.apache.mahout.math.VectorWritable;


public class RCV1Job extends Configured implements Tool {
    
  public static class Map extends Mapper<Object, Text, IntWritable, VectorWritable> {
  
    public void map(Object key, Text value, Context context) throws IOException, InterruptedException {
      // Randomly distribute to Reducers to get a random partitioning
      System.out.println(key);
//      context.write(word, one);
    }
  }

  /*
    class for Reduce
  */
  public static class Reduce extends Reducer<IntWritable, VectorWritable, IntWritable, Text> {
  
    public void reduce(IntWritable key, Iterable<VectorWritable> values, Context context) throws IOException, InterruptedException {
      // Train
      for (VectorWritable val : values) {
        
      }
//      context.write(key, result);
    }

  }
  
  public int run(String[] args) throws Exception {
//    if (args.length != 2) {
//      System.err.printf("Usage: %s [generic options] <input> <output>", getClass().getSimpleName());
//      ToolRunner.printGenericCommandUsage(System.err);
//      return -1;
//    }
//    String inputFile = args[0];
//    String outputDir = args[1];

    Job job = prepareJob();
  
    return job.waitForCompletion(true) ? 0 : 1;
  }
  
  private Job prepareJob() throws IOException {

    Job job = new Job(getConf(), "rcv1");
    job.setJarByClass(getClass());

    String inputFile = "";  // will be set depending on localmode or not
    String outputDir = "output-aim3";
    boolean runLocalMode = false;
    
    // Work with local information (not in local mode)
    // Requires building of the jar first: mvn package
    if (runLocalMode) {
      inputFile = "/home/andre/dev/datasets/RCV1-v2/vectors/lyrl2004_vectors_train_5000.dat";
    } else {
      // reads configuration in core-site.xml. hdfs for me
      inputFile = "rcv1-v2/lyrl2004_vectors_train_5000.dat";
      job.getConfiguration().addResource(new Path("core-site.xml"));
      job.getConfiguration().set("mapred.jar","target/aim3-logreg-0.0.1-SNAPSHOT.jar");
      
      // Delete old output dir
      FileSystem hdfs = FileSystem.get(job.getConfiguration());
      Path path = new Path(outputDir);
      hdfs.delete(path, true);
    }
    System.out.println("Jar: " + job.getJar());
    
    // Key/Value Type
    job.setOutputKeyClass(Text.class);
    job.setOutputValueClass(IntWritable.class);
  
    job.setMapperClass(Map.class);
    // Optional: Use local combiner (we have a combinable reducer)
    job.setCombinerClass(Reduce.class);
    job.setReducerClass(Reduce.class);
  
    // Input/Output Format
    // We use the default.
    // For file based input/output formats we can use the predefined FileInputFormat class
    // It has a generic implementation of getSplits()
    // One map tasks is spawned for each InputSplit generated by the InputFormat
    // see http://hadoop.apache.org/docs/current/api/org/apache/hadoop/mapred/InputFormat.html
    //job.setInputFormatClass(TextInputFormat.class);
    //job.setOutputFormatClass(TextOutputFormat.class);
  
    // configure the used input/output format class.
    FileInputFormat.addInputPath(job, new Path(inputFile));
    FileOutputFormat.setOutputPath(job, new Path(outputDir));
  
    // Set number of mappers and reducers manually
    // Not done here, will be done via command line parameter
    //conf.setNumMapTasks(4);
    //conf.setNumReduceTasks(2);
    
    return job;
  }

}
